### ISSUE TITLE
Inclusion of a label or header comment for each material type

### ISSUE THREAD

**Issue by RossWorrall** [ukaea/neutronics_material_maker#11]
Comments in MCNP after a definition must have a $ preceding them. c can only be used at the start of the line, when the whole line is a comment. 

Please could you include the option of adding a comment above each material, briefly stating what the material is.

E.G.

ccccccccccccccccccccccccccccccccccccccccccccccccccccc
c Li2O3 - Material in component X                                
ccccccccccccccccccccccccccccccccccccccccccccccccccccc
m3 -4.0
   3006        0.045540000000000004     $ Lithium_6\n'
   3007        0.5544600000000001         $ Lithium_7\n'
   8016        0.39902800000000005       $ Oxygen_16\n'
   8017        0.000152                             $ Oxygen_17\n'
   8018        0.0008200000000000001    $ Oxygen_18\n')

Thanks.

R

**Comment by shimwell** [comment]
Thanks Ross, I have tidied up the code and the comments are now as you describe.

A new variable called material_card_comment is now available and adds a comment above each line.

let me know what you think of the updated extra_neutronics_codes branch
