### ISSUE TITLE
adding scale material outputs

### ISSUE THREAD

**Issue by shimwell** [ukaea/neutronics_material_maker#110]
To allow shift material format to be exported we could add another function like this one that outputs mcnp materials

https://github.com/ukaea/neutronics_material_maker/blob/4ec3fcb5a7bfe321f0f3eab40c88f2822dee5551/neutronics_material_maker/utils.py#L81-L127

then we could add a new property for the scale shift export in materials.py like this one that does mcnp
https://github.com/ukaea/neutronics_material_maker/blob/4ec3fcb5a7bfe321f0f3eab40c88f2822dee5551/neutronics_material_maker/material.py#L285-L299

and another in the multimaterial class like this one
https://github.com/ukaea/neutronics_material_maker/blob/4ec3fcb5a7bfe321f0f3eab40c88f2822dee5551/neutronics_material_maker/mutlimaterial.py#L205-L217

what do you think @jbae11 does this look like the best option

**Comment by jbae11** [comment]
@Shimwell is there a dictionary of isotopic atomic mass (e.g. {'h1': 1.0078})?

So Shift's material composition unit is [atoms/barn-cm], meaning that the material density is 'baked into' the material definition, which is different than MCNP. Thus I'd need the atomic mass to convert from `wo`. If there isn't a dictionary of isotopic atomic mass, I think I have one, I can add that in the `utils.py` as well. Let me know :)

**Comment by shimwell** [comment]
Perhaps openmc.Material().get_nuclide_atom_densities() is useful here

**Comment by shimwell** [comment]
solved in #114
