### ISSUE TITLE
Version inconsistency

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [ukaea/neutronics_material_maker#139]
The latest pypi version is 0.3.2 whereas the github release tag is 0.1.13 

https://pypi.org/project/neutronics-material-maker/0.3.2/
https://github.com/ukaea/neutronics_material_maker/releases/tag/v0.1.13

Is it possible to trigger the pypi build on a github release?

**Comment by shimwell** [comment]
Thanks for the nudge. You might be happy to know that the next merge from develop to main changes the way PyPi is updated. It will make use of GitHub releases to trigger PyPi releases so they should be kept consistent from now on

https://github.com/ukaea/neutronics_material_maker/blob/823207e4c8ddf61c7316c96d408af283cb6b0b79/.github/workflows/python-publish.yml#L6-L8

**Comment by shimwell** [comment]
v0.3.2 now released on GitHub https://github.com/ukaea/neutronics_material_maker/releases/tag/v0.3.2

**Comment by RemDelaporteMathurin** [comment]
> Thanks for the nudge. You might be happy to know that the next merge from develop to main changes the way PyPi is updated. It will make use of GitHub releases to trigger PyPi releases so they should be kept consistent from now on
> 
> https://github.com/ukaea/neutronics_material_maker/blob/823207e4c8ddf61c7316c96d408af283cb6b0b79/.github/workflows/python-publish.yml#L6-L8

Interesting!
