### ISSUE TITLE
Verbosity

### ISSUE THREAD

**Issue by CoronelBuendia** [ukaea/neutronics_material_maker#2]
Started using nmm now in BLUEPRINT. It is probably working fine, but the print statements are clogging up my console!

I propose to add a kwarg in the base class:
```python
class NamedObject(object):
    def __init__(self, **kwargs):
        self.verbose = kwargs.get('verbose', False)
        self.classname = self.__class__.__name__
```
```python
class Isotope(NamedObject):
    def __init__(self, symbol_or_proton, atomic_number, abundance='Natural', **kwargs):
        super(Isotope, self).__init__(**kwargs)
```
and then, e.g.
```python
    @property
    def isotopes(self):
        if self.verbose:
                print(self.description)
                print(self.element_atom_fractions)
        list_of_isotopes = []
```

What do you think? Happy to try and submit a pull request for this, but don't want to break the pip install (see Issue #1 )

**Comment by shimwell** [comment]
Yes please this looks nice, 

If you submit the pull request I can grab the code and upload a new pip version
