### ISSUE TITLE
Feature request : enriched_isotopes for materials

### ISSUE THREAD

**Issue by daleher** [ukaea/neutronics_material_maker#27]
Whereas in Compounds an isotopic Enrichment can be specified, Materials do not accept this Enriched Isotopes option.

```
mat_PbLi = Material(material_card_name = 'PbLi',
					density_g_per_cm3 = 10,
					elements = [Element('Li'),
    				            Element('Pb')],
    				element_mass_fractions = [0.01,
    										  0.99],
                    enriched_isotopes=[Isotope('Li', 6, 0.9),
                                     Isotope('Li', 7, 0.1)])
```

**Comment by shimwell** [comment]
Thanks for mentioning this issue.
The enriched_isotopes card is not currently supported by the Material class

However the enriched_isotope card is supported by the Element class so you could construct an enriched Element and add it to the list of Elements in the Material.

I have added an example to the documentation

```
example_element = Element('Li',
                          enriched_isotopes=[Isotope('Li', 7, abundance=0.4),
                                                Isotope('Li', 6, abundance=0.6)])
```

Let me know if this is satisfactory for you.

**Comment by daleher** [comment]
It works perfectly fine.

Thanks for the feedback, it was very useful!
