### ISSUE TITLE
Composition of units for SS316L N IG are set as 'ao' but appear to be 'wo'

### ISSUE THREAD

**Issue by Sophia-vT** [ukaea/neutronics_material_maker#45]
Comparing the composition of SS316L N IG in wt.% with the composition OpenMC uses which is set as at.%, for a number of nuclei, it appears that it should be wt.% rather than at.%.
For example, the material contains:
0.03 wt.% of C , given in openmc as 0.03 at.%
0.01 wt.% Nb93, in openmc it gives 0.01 at.%
0.05 wt.% Co59, in openmc 0.05 at.%.
similar case with tantalum, Mn55.

Not sure if all the units were put as atomic percent rather than weight percent by mistake, or if it just wrong for some nuclides. Attached is the composition from openmc.
[SS316LNIG_composition_openmc .pdf](https://github.com/ukaea/neutronics_material_maker/files/5007986/SS316LNIG_composition_openmc.pdf)

**Comment by shimwell** [comment]
Thanks for reporting this, this has now been fixed with the recent upgrade to v 0.1.2
