### ISSUE TITLE
C or K

### ISSUE THREAD

**Issue by CoronelBuendia** [ukaea/neutronics_material_maker#7]
I based everything in Kelvin, before realising that I think in Celsius, and all the equations in the ITER material props references I can find are in Celsius. So I think I made a booboo. 

Thoughts? Anything you can think of that might use Kelvin apart from SC materials?

**Comment by shimwell** [comment]
I think the equations for finding density of the coolant at different pressures and temperatures also use Kelvin at the moment. I can change them to degrees C. Either is good for me

**Comment by CoronelBuendia** [comment]
Ach! Kelvin it is :) If need be we can write some sort of ghost-like wrapper for the whole thing which treats temperatures as C or K, depending on which variant of the class/user-setting(?) the user chooses.
