### ISSUE TITLE
License not included in tarball

### ISSUE THREAD

**Issue by dopplershift** [ukaea/neutronics_material_maker#80]
`Manifest.in` lists `LICENSE` which doesn't exist. It should say `LICENSE.txt` instead.

**Comment by shimwell** [comment]
Thanks for that, I have updating accordingly

**Comment by shimwell** [comment]
Also updated the pypi tarball and downloaded it to check it contains the LICENSE.txt
Then updated the conda recipe to include the new PYPI version number and sha256

Thanks for the help with the conda forge process
